services:
  LEA-Bot:
    image: lea-bot
    build:
      context: .
      args:
        webPort: ${webPort}
    container_name: LEA-Bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/db
    ports:
      - "${webPort}:${webPort}"
    networks:
      - Cordos

networks:
  Cordos:
    external: true
